# Generated by Django 4.1.3 on 2022-11-30 00:47

from django.db import migrations, models
import django_cpf_cnpj.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação: ')),
                ('nome', models.CharField(max_length=120)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('nascimento', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('telefone_principal', models.CharField(max_length=11)),
                ('telefone_alternativo', models.CharField(blank=True, max_length=11)),
                ('descricao', multiselectfield.db.fields.MultiSelectField(choices=[('ABERTURA MEI', 'FORMALIZAÇÃO'), ('ALTERAÇÃO CADASTRAL', 'ALTERAÇÃO CADASTRAL'), ('INFORMAÇÕES', 'INFORMAÇÕES'), ('EMISSÃO DAS', 'EMISSÃO DAS'), ('PARCELAMENTO', 'PARCELAMENTO'), ('EMISSÃO DE PARCELA', 'EMISSÃO DE PARCELA'), ('CÓDIGO DE ACESSO', 'CÓDIGO DE ACESSO'), ('REGULARIZE', 'REGULARIZE'), ('BAIXA MEI', 'BAIXA MEI'), ('REGISTRO BAIXADO', 'REGISTRO BAIXADO')], max_length=100)),
                ('tipo', models.CharField(choices=[('ON-LINE', 'ON-LINE'), ('PRESENCIAL', 'PRESENCIAL')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
